name = "XMin"
license = "MIT"
licenselink = "https://github.com/brangpd/hugo-xmin/blob/master/LICENSE.md"
description = "eXtremely Minimal Hugo theme: about 150 lines of code in total, including HTML and CSS"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.19"

[author]
  name = "brangpd"
