baseurl = "/blog"
languageCode = "zh-Hans"
title = "花落无声的站点"
theme = "hugo-xmin-brangpd"
enableGitInfo = true

googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↑"
paginate = 10
enableEmoji = true
hasCJKLanguage = true
summaryLength = 100
pygmentsUseClasses = true

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
    identifier = "home"
[[menu.main]]
    name = "近期"
    url = "/p/"
    weight = 2
    identifier = "posts"
[[menu.main]]
    name = "全部"
    url = "/pall/"
    weight = 3
    identifier = "all_posts"
[[menu.main]]
    name = "归档"
    url = "/categories/"
    weight = 4
    identifier = "categories"
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 5
    identifier = "tags"
[[menu.main]]
    name = "订阅"
    url = "/index.xml"
    weight = 6
    identifier = "subcribe"

[permalinks]
    posts = "/posts/:year/:month/:day/:slug/"
    notes = "/notes/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "brangpd's blog"
    dateformat = "2006.01.02 15:04:05"
    katex = true
    author = "花落无声@brangpd"
    commentrepo = "brangpd/repo-for-comment"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      xhtml = true
      hardWraps = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  [markup.highlight]
    codeFences = true
    lineNos = true
    tabWidth = 2
